default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  
development:
  <<: *default
  database: invoiced_development
test:
  <<: *default
  database: invoiced_test

production:
  <<: *default
  database: invoiced_production
  username: invoiced
  password: <%= ENV['INVOICED_DATABASE_PASSWORD'] %>
